internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

internet_shop/main/urls.py
from .views import CatalogView, ClothingItemDetailView
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
    path('item/<slug:slug>/', ClothingItemDetailView.as_view(), name='clothing_item_detail')
]

internet_shop/main/models.py
from django.db import models

class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_item_count(self):
        return ClothingItem.objects.filter(category=self).count()
    

class ClothingItem(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    available = models.BooleanField(default=True)
    sizes = models.ManyToManyField(Size, through='ClothingItemSize', related_name='clothing_item', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='clothing_items')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

    def get_price_with_discount(self):
        if self.discount > 0:
            return self.price * (1 - (self.discount / 100))
        return self.price

class ClothingItemSize(models.Model):
    clothing_item = models.ForeignKey(ClothingItem, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    class Meta:
        unique_together = ('clothing_item', 'size')

class ItemImage(models.Model):
    product = models.ForeignKey(ClothingItem, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

internet_shop/main/views.py
from django.views.generic import ListView, DetailView
from .models import ClothingItem, Category, Size, ClothingItemSize
from django.db.models import Q

class CatalogView(ListView):
    model = ClothingItem
    template_name = 'main/product/list.html'
    context_object_name = 'clothing_items'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_slugs = self.request.GET.getlist('category')
        size_names = self.request.GET.getlist('size')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        if category_slugs:
            queryset = queryset.filter(category__slug__in=category_slugs)

        if size_names:
            queryset = queryset.filter(Q(sizes__name__in=size_names) & Q(sizes__clothingitemsize__available=True)).distinct()

        if min_price:
            queryset = queryset.filter(price__gte=min_price)

        if max_price:
            queryset = queryset.filter(price__lte=max_price)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['sizes'] = Size.objects.all()
        context['selected_categories'] = self.request.GET.getlist('category')
        context['selected_sizes'] = self.request.GET.getlist('size')
        context['min_price'] = self.request.GET.get('min_price', '')
        context['max_price'] = self.request.GET.get('max_price', '')

        return context

class ClothingItemDetailView(DetailView):
    model = ClothingItem
    template_name = 'main/product/detail.html'
    context_object_name = 'clothing_item'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clothing_item = self.object
        available_sizes = ClothingItemSize.objects.filter(clothing_item=clothing_item, available=True)
        context['available_sizes'] = available_sizes
        return context

internet_shop/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header class="header sticky-top d-flex align-items-center">
        <div class="header-logo">
            <img src="{% static 'img/rev.png' %}" alt="">
        </div>
        {% comment %} <div class="search">
            <form action="" id="search-form" class="search_form d-flex" style="display: none;">
                <input type="text" name="q" class="form_input" placeholder="Search">
                <button type="submit" class="btnforsearch"></button>
            </form>
        </div> {% endcomment %}
        <div class="header-nav d-flex gap-4">
            <a href="#" class="h-profile">
                <img src="{% static 'img/profile.png' %}" alt="">
            </a>
            <a href="#" class="h-profile">
                <img src="{% static 'img/cart.png' %}" alt="">
            </a>
            <div class="forsearch">
                <a href="#" id="toggle-search" class="toggle-search">
                    <img src="{% static 'img/search.png' %}" alt="">
                </a>
                <div class="search-popup" id="search-popup" style="display: none;">
                    <form class="search-form" method="GET" action="" id="search-form">
                        <div class="input-container">
                            <input type="text" class="form_input" name="q" placeholder="Search">
                            <button type="submit" class="btn"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </header>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script>
        document.getElementById('toggle-search').addEventListener('click', function(event) {
            event.preventDefault();
            const searchPopup = document.getElementById('search-popup');

            if (searchPopup.style.display === 'none' || searchPopup.style.display === '') {
                searchPopup.style.display = 'block';
            } else {
                searchPopup.style.display = 'none';
            }
        });
    </script>

    {% comment %} js for bootstrap {% endcomment %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

internet_shop/main/templates/main/product/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}{{ clothing_item.name }}{% endblock title %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="detail-img d-flex justify-content-center">
            {% for image in clothing_item.images.all %}
                <img src="{{ image.image.url }}" style="display: none;" alt="{{ clothing_item.name }}" class="detail-image" data-index="{{ forloop.counter0 }}">
            {% endfor %}
            <div class="image-nav">
                <button class="prev-btn">&lsaquo;</button>
                <button class="next-btn">&rsaquo;</button>
            </div>
        </div>

        <div class="detail-description">
            <h2>{{ clothing_item.name }}</h2>
            <h3 class="item-desc">{{ clothing.item.description|linebreaks }}</h3>
            <div class="sizes">
                <p>Available Sizes:
                    <ul class="sizes-list d-flex gap-3">
                        {% for item_size in available_sizes %}
                            <li class="size-name d-flex justify-content-center align-items-center" data-size="{{ item_size.size.name }}">
                                {{ item_size.size.name }}
                            </li>
                        {% empty %}
                            <li>No available sizes.</li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
            {% if clothing_item.discount %}
                <div class="cart-discount d-flex gap-2">
                    <p class="line">${{ clothing_item.price }}</p>
                    <p class="price">${{ clothing_item.get_price_with_discount }}</p>
                </div>
            {% else %}
                <p class="detail-price">
                    ${{ clothing_item.price }}
                </p>
            {% endif %}
            <div class="detail-cart-form">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="select-size d-flex gap-2">
                        <label for="size">Size:</label>
                        <div id="size-display">
                            unselected
                        </div>
                    </div>
                    <input type="hidden" name="size" id="size" required>
                    <button type="submit" class="default-btn mt-3">Add to cart</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        const sizeItems = document.querySelectorAll('.size-name');
        const sizeDisplay = document.getElementById('size-display');
        const sizeInput = document.getElementById('size')

        sizeItems.forEach(item => {
            item.addEventListener('click', () => {
                sizeInput.value = item.getAttribute('data-size');
                sizeDisplay.textContent = item.getAttribute('data-size');
                sizeItems.forEach(i => i.classList.remove('detail-selected'));
                item.classList.add('detail-selected');

            });
        });

        const images = document.querySelectorAll('.detail-image');
        const prevBtn = document.querySelector('.prev-btn');
        const nextBtn = document.querySelector('.next-btn');
        let currentIndex = 0;

        if (images.length > 0) {
            images[currentIndex].style.display = 'block';

            if (images === 1) {
                prevBtn.style.display = 'none';
                nextBtn.style.display = 'none';
            } else {
                prevBtn.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex - 1 + images.length) % images.length;
                    images[currentIndex].style.display = 'block';
                });

                nextBtn.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex + 1) % images.length;
                    images[currentIndex].style.display = 'block';
                });
            }
        }
    </script>
{% endblock content %}

internet_shop/main/templates/main/product/list.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}internet-shop{% endblock title %}
{% block content %}
    <h1 class="rev-head text-uppercase" id="internet-shop-title">internet shop - ALL</h1>
    <div class="catalog d-flex">
        <form action="{% url 'main:catalog' %}" method="GET" class="sidebar" id="filter-form">
            <h4 class="price-head">Price Range:</h4>
            <div class="price-range d-flex justify-content-between">
                <input type="number" name="min_price" id="min_price" placeholder="Min Price" value="{{ request.GET.min_price }}" oninput="debounceApplyFilters()">
                <input type="number" name="max_price" id="max_price" placeholder="Max Price" value="{{ request.GET.max_price }}" oninput="debounceApplyFilters()">
            </div>

            <h4 class="category-head">Category:</h4>
            {% for category in categories %}
                <div class="category-option">
                    <input type="checkbox" name="category" id="category-{{ category.slug }}" value="{{ category.slug }}"
                    {% if category.slug in selected_categories %}checked{% endif %} onchange="">
                    <label for="category-{{ category.slug }}" class="d-flex">
                        <div class="category-name">{{ category.name }}</div> <div class="category-len">{{ category.get_item_count }}</div>
                    </label>
                </div>
            {% endfor %}

            <h4 class="size-head">Size:</h4>
            {% for size in sizes %}
                <div class="category-option">
                    <input type="checkbox" name="size" id="size-{{ size.name }}" value="{{ size.name }}"
                    {% if size.name in selected_sizes %}checked{% endif %} onchange="">
                    <label for="size-{{ size.name }}">{{ size.name }}</label>
                </div>
            {% endfor %}

        </form>

        <div class="product-list">
            <div class="card-container d-flex flex-wrap">
                {% for item in clothing_items %}
                    <div class="card">
                        {% if item.image %}
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="product-image">
                        {% endif %}
                        <div class="card-info">
                            <h5>{{ item.name }}</h5>
                            <p>${{ item.get_price_with_discount }}</p>
                        </div>
                    </div>
                {% empty %}
                    <p>No products.</p>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const checkboxes = document.querySelectorAll('.category-option input[type="checkbox"]');
            const form = document.getElementById('filter-form');

            checkboxes.forEach(checkbox => {
                checkbox.addEventListener('change', function() {
                    form.submit();
                });
            });
        });

        let timeout;
        function debounceApplyFilters() {
            clearTimeout(timeout);
            timeout = setTimeout(() => {
                const form = document.getElementById('filter-form');
                form.submit();
            }, 1000);
        }

        function applyFilters() {
            const form = document.getElementById('filter-form');
            form.submit();
            updateTitle();
        }

        function updateTitle() {
            const checkboxes = document.querySelectorAll('.category-option input[name="category"]:checked');
            const titleElement = document.getElementById('internet-shop-title');

            if (checkboxes.length > 0) {
                const selectedCategories = Array.from(checkboxes).map(checkbox => {
                    const categoryText = checkbox.nextElementSibling.textContent.trim();
                    return categoryText;
                });
                titleElement.textContent = `internet shop - ${selectedCategories.join(', ')}`;
            } else {
                titleElement.textContent = 'internet shop - ALL';
            }
        }

        document.addEventListener('DOMContentLoaded', updateTitle);
    </script>
{% endblock content %}